apiVersion: v1
kind: Secret
metadata:
  name: ecg-storage-consumer-db
  namespace: ecg-system
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: ecg-postgres
    app.kubernetes.io/part-of: ecg-platform
    app.kubernetes.io/component: database-credentials
type: kubernetes.io/basic-auth
stringData:
  POSTGRES_DB: "ecg"
  username: ecg_app
  password: REPLACE_ME # Secret manager must be used in production setup