apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ecg-kafka
  namespace: observability
  labels:
    app.kubernetes.io/name: ecg-kafka
    app.kubernetes.io/part-of: ecg-platform
spec:
  namespaceSelector:
    matchNames:
      - kafka
  selector:
    matchLabels:
      strimzi.io/cluster: ecg-kafka
      strimzi.io/kind: Kafka
  podMetricsEndpoints:
    - port: tcp-prometheus
      path: /metrics
      interval: 30s