apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka
  labels:
    strimzi.io/cluster: ecg-kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: ecg-kafka
    app.kubernetes.io/part-of: ecg-platform
spec:
  replicas: 3
  roles:
    - controller
    - broker
  # For demo purposes dual-role nodes were created
  # Create separate controller and broker nodes in production
  resources:
    requests:
      cpu: 250m
      memory: 768Mi
    limits:
      cpu: "1"
      memory: 1536Mi
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        class: kafka-local-storage
        size: 10Gi
        deleteClaim: false
        kraftMetadata: shared
        # For production it is recommended to use network-attached block storage such as
        # AWS EBS or GCP Persistent Disk