apiVersion: v1
kind: Service
metadata:
  name: grpc-stream-adapter
  namespace: ecg-system
  labels:
    app.kubernetes.io/name: grpc-stream-adapter
    app.kubernetes.io/component: ingestion
    app.kubernetes.io/part-of: ecg-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grpc-stream-adapter
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP