apiVersion: v1
kind: ConfigMap
metadata:
  name: ecg-generator-config
  namespace: ecg-system
data:
  GRPC_TARGET: "grpc-stream-adapter.ecg-system.svc.cluster.local:50051"
  SOURCE_ID: "mock-device-001"
  SESSION_ID: ""
  SAMPLING_RATE: "500"
  LEAD_ID: "II"
  CHUNKS_COUNT: "100"
  CHUNK_DURATION_SECONDS: "1"
  SEND_INTERVAL_SECONDS: "0.05"
  SKIP_CHUNK_INDEX: "-1"
  LOG_LEVEL: "INFO"